language: android
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3

    # SDK Version for Testing on
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-28

script:
  - ./gradlew assemble